[package]
name = "essential-constraint-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "2.1.0"
essential-constraint-asm = { workspace = true }
essential-types = { workspace = true }
rayon = "1"
sha2 = { workspace = true }
thiserror = "1"
