[package]
edition = "2021"
name = "test-utils"
version = "0.1.0"

[dependencies]
essential-types = { workspace = true }
utils = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
