[workspace]
members = ["crates/essential"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.80"
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
tokio = { version = "1.36.0", features = ["full"] }