[workspace]
members = [
  "crates/*"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.80"
base64 = "0.22.0"
essential-constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
postcard = { version = "1.0.8", default-featues = false, features = ["alloc"] }
reqwest = "0.12.0"
secp256k1 = { version = "0.28.2", features = ["rand-std", "hashes-std"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
tokio = { version = "1.36.0", features = ["full"] }

constraint-vm = { path = "crates/constraint-vm", package = "essential-constraint-vm" }
memory-storage = { path = "crates/memory-storage" }
storage = { path = "crates/storage" }
test-utils = { path = "crates/test_utils" }
utils = { path = "crates/utils" }
