[workspace]
members = [
    "crates/essential",
    "crates/memory-storage",
    "crates/placeholder",
    "crates/rlite-storage",
    "crates/storage",
    "crates/utils",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.80"
essential-constraint-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-state-asm = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }

memory-storage = { path = "crates/memory-storage" }
placeholder = { path = "crates/placeholder" }
storage = { path = "crates/storage" }
test-utils = { path = "crates/test_utils" }
utils = { path = "crates/utils" }
