[package]
edition = "2021"
name = "utils"
version = "0.1.0"

[dependencies]
essential-types = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
