[package]
edition = "2021"
name = "memory-storage"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
essential-types = { workspace = true }
placeholder = { workspace = true }
storage = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
test-utils = { workspace = true }
tokio = { workspace = true }
