[package]
edition = "2021"
name = "essential"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
essential-types = { workspace = true }
tokio = { workspace = true }