[package]
edition = "2021"
name = "essential-rest-server"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
clap = { workspace = true }
essential-server = { workspace = true }
essential-types = { workspace = true }
futures = { workspace = true }
memory-storage = { workspace = true }
rqlite-storage = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
storage = { workspace = true }
test-utils = { workspace = true }
utils = { workspace = true }
