[package]
edition = "2021"
name = "essential-rest-server"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
essential-server = { workspace = true }
essential-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
memory-storage = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
test-utils = { workspace = true }
utils = { workspace = true }
