name: release 

on:
    push:
      tags:
        - "v*.*.*"
        - "v*.*.*-*"

jobs:
  build:
    permissions:
      id-token: "write" # added for magic-nix-cache-action
      contents: "read"  # added for magic-nix-cache-action
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH 
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}
              ${{ secrets.SSH_PRIVATE_KEY_SELF }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Cache Nix
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: nix build --print-build-logs --no-update-lock-file .#essential-rest-server
      - uses: actions/upload-artifact@v4
        with:
          name: essential-rest-server-${{ matrix.os }}
          path: ./result/bin/essential-rest-server
    
  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            path: ${{ github.workspace }}/bin
            merge-multiple: true
      - name: Release 
        uses: softprops/action-gh-release@v2
        with:
            files: |
                ${{ github.workspace }}/bin/essential-rest-server-ubuntu-latest
                ${{ github.workspace }}/bin/essential-rest-server-macos-latest